### ISSUE TITLE
Add test documents for integration reporting

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla-services/edge-validator#23]
Currently, AWS credentials are required to pull down sample documents for integration testing against `mozilla-services/mozilla-pipeline-schemas`. It should be possible to run integration testing without special credentials. 

There is currently a test schema that is used to test that the system is live. The quick-start guide mentions that data conforming to the following schema can be used for testing.

https://github.com/mozilla-services/edge-validator/blob/bf19eede36c336ffad1b01de695ab67a404c0130/tests/resources/schemas/testing/test/test.1.schema.json#L1-L15

There should be a corresponding `tests/resources/data/testing/test.1.batch.json` document for verifying the output of the `integration.py` script.

This file has one line per document, where each document is json delimited by a newline. There should be passing and failing examples. The result of running the report on this document should be known ahead of time.

**Comment by erindcole** [comment]
I'd like to work on this issue. I am not able to assign it to myself, but I'll get started on it.

**Comment by acmiyaguchi** [comment]
I've added a few documents to the testing resource folder.

https://github.com/mozilla-services/edge-validator/blob/915b2c1cf8a6176bd30a26529290cb651d1f3ddf/tests/resources/data/testing/test/test.1.batch.json#L1-L3

These documents can be used for testing without pulling down external dependencies.
